# VisualTracePipeline Configuration

gemma:
  model_id: google/gemma-3-1b-it

grounded_sam:
  grounding_model: IDEA-Research/grounding-dino-base
  box_threshold: 0.4
  text_threshold: 0.3
  mask_selection:
    enabled: false
    top_k: 3

sam2:
  model_id: facebook/sam2-hiera-large

cotracker:
  model_id: facebookresearch/co-tracker:cotracker3_offline
  keypoints_per_mask: 3  # Number of keypoints to extract from each mask
  grid_size: 0
  grid_query_frame: 0

keypoint_tracker:
  model_id: cotracker  # Options: "cotracker" or "sam2"

keypoint_filter:
  traj_top_k: 3
  traj_drop_use_median : true
  traj_drop_len_ratio : 0.1

robot_gripper:
  enabled: true
  prompt: "the gripper at the end of the robotic arm"
