# VisualTracePipeline Configuration

gemma:
  model_id: google/gemma-3-1b-it

sam2:
  model_id: facebook/sam2-hiera-large

cotracker:
  model_id: facebookresearch/co-tracker:cotracker3_offline

keypoint_filter:
  traj_top_k: 3
  traj_drop_use_median : true
  traj_drop_len_ratio : 0.1